import { useState, useMemo } from 'react';
import type { AuditResult, Severity } from '../types';
import RiskScore from './RiskScore';
import { SeverityCount } from './SeverityBadge';
import FindingCard from './FindingCard';

interface ReportProps {
  result: AuditResult;
  onNewAudit: () => void;
}

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M2 11v2a1 1 0 001 1h10a1 1 0 001-1v-2M8 2v9M5 8l3 3 3-3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const min = Math.floor(seconds / 60);
  const sec = seconds % 60;
  return `${min}m ${sec.toFixed(0)}s`;
}

export default function Report({ result, onNewAudit }: ReportProps) {
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [activeSeverity, setActiveSeverity] = useState<Severity | null>(null);

  const severityCounts = useMemo(() => {
    const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    result.findings.forEach((f) => {
      counts[f.severity]++;
    });
    return counts;
  }, [result.findings]);

  const categories = useMemo(() => {
    const cats = new Set<string>();
    result.findings.forEach((f) => cats.add(f.category));
    return Array.from(cats);
  }, [result.findings]);

  const filteredFindings = useMemo(() => {
    let findings = [...result.findings];
    if (activeCategory) {
      findings = findings.filter((f) => f.category === activeCategory);
    }
    if (activeSeverity) {
      findings = findings.filter((f) => f.severity === activeSeverity);
    }
    // Sort by severity
    findings.sort(
      (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
    );
    return findings;
  }, [result.findings, activeCategory, activeSeverity]);

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codescope-${result.repo_name.replace('/', '-')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadMarkdown = () => {
    let md = `# CodeScope Security Report\n\n`;
    md += `**Repository:** ${result.repo_name}\n`;
    md += `**Branch:** ${result.branch}\n`;
    md += `**Risk Score:** ${result.risk_score}/100\n`;
    md += `**Date:** ${new Date().toISOString().split('T')[0]}\n\n`;
    md += `## Summary\n\n${result.summary}\n\n`;
    md += `## Findings (${result.findings.length})\n\n`;

    SEVERITY_ORDER.forEach((sev) => {
      const findings = result.findings.filter((f) => f.severity === sev);
      if (findings.length === 0) return;
      md += `### ${sev.toUpperCase()} (${findings.length})\n\n`;
      findings.forEach((f) => {
        md += `- **${f.title}**`;
        if (f.file) md += ` \`${f.file}${f.line > 0 ? `:${f.line}` : ''}\``;
        md += `\n  ${f.description}\n`;
        md += `  *Fix:* ${f.fix}\n\n`;
      });
    });

    md += `---\n*Generated by CodeScope / Ephemeral.ai*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codescope-${result.repo_name.replace('/', '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-3xl mx-auto px-6 pt-12 pb-20 animate-fade-in">
      {/* Header */}
      <div className="flex items-start justify-between mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h2 className="text-lg font-semibold text-text-primary">Report</h2>
            <span className="font-mono text-accent-purple text-sm">{result.repo_name}</span>
          </div>
          <div className="flex items-center gap-3 text-xs font-mono text-text-secondary">
            <span>branch: {result.branch}</span>
            <span className="text-border">|</span>
            <span>{result.language}</span>
            <span className="text-border">|</span>
            <span>{formatDuration(result.duration_seconds)}</span>
            <span className="text-border">|</span>
            <span className="text-accent-green">${result.cost_usd.toFixed(3)}</span>
          </div>
        </div>
        <button
          onClick={onNewAudit}
          className="text-xs text-text-secondary hover:text-text-primary transition-colors font-mono px-3 py-1.5 border border-border rounded-lg hover:border-text-muted"
        >
          New Audit
        </button>
      </div>

      {/* Risk Score */}
      <div className="border border-border rounded-lg bg-surface p-5 mb-6">
        <div className="text-2xs font-semibold text-text-secondary uppercase tracking-wider mb-3">
          Risk Score
        </div>
        <RiskScore score={result.risk_score} />
      </div>

      {/* Severity Counts */}
      <div className="flex flex-wrap gap-3 mb-6">
        {SEVERITY_ORDER.map((sev) => (
          <button
            key={sev}
            onClick={() => setActiveSeverity(activeSeverity === sev ? null : sev)}
            className={`transition-opacity ${
              activeSeverity && activeSeverity !== sev ? 'opacity-40' : ''
            } hover:opacity-100`}
          >
            <SeverityCount severity={sev} count={severityCounts[sev]} />
          </button>
        ))}
      </div>

      {/* AI Summary */}
      <div className="border border-border rounded-lg bg-surface p-5 mb-6">
        <div className="text-2xs font-semibold text-text-secondary uppercase tracking-wider mb-2">
          AI Analysis Summary
        </div>
        <p className="text-sm text-text-secondary leading-relaxed">{result.summary}</p>
      </div>

      {/* Category Filters */}
      <div className="flex flex-wrap gap-2 mb-4">
        <button
          onClick={() => setActiveCategory(null)}
          className={`px-2.5 py-1 text-2xs font-mono rounded border transition-colors ${
            activeCategory === null
              ? 'bg-accent-purple/10 border-accent-purple/30 text-accent-purple'
              : 'bg-surface border-border text-text-secondary hover:border-text-muted'
          }`}
        >
          All ({result.findings.length})
        </button>
        {categories.map((cat) => {
          const count = result.findings.filter((f) => f.category === cat).length;
          return (
            <button
              key={cat}
              onClick={() => setActiveCategory(activeCategory === cat ? null : cat)}
              className={`px-2.5 py-1 text-2xs font-mono rounded border transition-colors ${
                activeCategory === cat
                  ? 'bg-accent-purple/10 border-accent-purple/30 text-accent-purple'
                  : 'bg-surface border-border text-text-secondary hover:border-text-muted'
              }`}
            >
              {cat} ({count})
            </button>
          );
        })}
      </div>

      {/* Findings */}
      <div className="space-y-2 mb-8">
        {filteredFindings.map((finding) => (
          <FindingCard key={finding.id} finding={finding} />
        ))}
        {filteredFindings.length === 0 && (
          <div className="text-center py-8 text-sm text-text-muted font-mono">
            No findings match the selected filters.
          </div>
        )}
      </div>

      {/* Scan Layers Summary */}
      <div className="border border-border rounded-lg bg-surface overflow-hidden mb-8">
        <div className="px-4 py-3 border-b border-border">
          <span className="text-2xs font-semibold text-text-secondary uppercase tracking-wider">
            Scan Layers
          </span>
        </div>
        {result.layers.map((layer, idx) => (
          <div
            key={layer.id}
            className={`flex items-center gap-3 px-4 py-2.5 text-sm ${
              idx < result.layers.length - 1 ? 'border-b border-border' : ''
            }`}
          >
            <span className="text-accent-green text-xs">&#9679;</span>
            <span className="text-2xs font-mono text-text-muted w-4">{layer.id}</span>
            <span className="flex-1 text-text-primary text-sm">{layer.name}</span>
            <span className="text-xs font-mono text-text-secondary">
              {layer.findings} findings
            </span>
            <span className="text-xs font-mono text-text-muted w-12 text-right">
              {layer.duration?.toFixed(1)}s
            </span>
          </div>
        ))}
      </div>

      {/* Download Actions */}
      <div className="flex flex-wrap gap-3">
        <button
          onClick={downloadMarkdown}
          className="flex items-center gap-2 px-4 py-2 text-sm font-mono text-text-secondary bg-surface border border-border rounded-lg hover:border-text-muted hover:text-text-primary transition-colors"
        >
          <DownloadIcon />
          Download Report
        </button>
        <button
          onClick={downloadJSON}
          className="flex items-center gap-2 px-4 py-2 text-sm font-mono text-text-secondary bg-surface border border-border rounded-lg hover:border-text-muted hover:text-text-primary transition-colors"
        >
          <DownloadIcon />
          Download JSON
        </button>
      </div>
    </div>
  );
}
