import { useState, useMemo } from 'react';
import type { AuditResult, Severity } from '../types';
import RiskScore from './RiskScore';
import { SeverityCount } from './SeverityBadge';
import FindingCard from './FindingCard';

interface ReportProps {
  result: AuditResult;
  onNewAudit: () => void;
}

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M2 11v2a1 1 0 001 1h10a1 1 0 001-1v-2M8 2v9M5 8l3 3 3-3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const min = Math.floor(seconds / 60);
  const sec = seconds % 60;
  return `${min}m ${sec.toFixed(0)}s`;
}

export default function Report({ result, onNewAudit }: ReportProps) {
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [activeSeverity, setActiveSeverity] = useState<Severity | null>(null);

  const severityCounts = useMemo(() => {
    const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    result.findings.forEach((f) => {
      counts[f.severity]++;
    });
    return counts;
  }, [result.findings]);

  const categories = useMemo(() => {
    const cats = new Set<string>();
    result.findings.forEach((f) => cats.add(f.category));
    return Array.from(cats);
  }, [result.findings]);

  const filteredFindings = useMemo(() => {
    let findings = [...result.findings];
    if (activeCategory) {
      findings = findings.filter((f) => f.category === activeCategory);
    }
    if (activeSeverity) {
      findings = findings.filter((f) => f.severity === activeSeverity);
    }
    // Sort by severity
    findings.sort(
      (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
    );
    return findings;
  }, [result.findings, activeCategory, activeSeverity]);

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codescope-${result.repo_name.replace('/', '-')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadMarkdown = () => {
    let md = `# CodeScope Security Report\n\n`;
    md += `**Repository:** ${result.repo_name}\n`;
    md += `**Branch:** ${result.branch}\n`;
    md += `**Risk Score:** ${result.risk_score}/100\n`;
    md += `**Date:** ${new Date().toISOString().split('T')[0]}\n\n`;
    md += `## Summary\n\n${result.summary}\n\n`;
    md += `## Findings (${result.findings.length})\n\n`;

    SEVERITY_ORDER.forEach((sev) => {
      const findings = result.findings.filter((f) => f.severity === sev);
      if (findings.length === 0) return;
      md += `### ${sev.toUpperCase()} (${findings.length})\n\n`;
      findings.forEach((f) => {
        md += `- **${f.title}**`;
        if (f.file) md += ` \`${f.file}${f.line > 0 ? `:${f.line}` : ''}\``;
        md += `\n  ${f.description}\n`;
        md += `  *Fix:* ${f.fix}\n\n`;
      });
    });

    md += `---\n*Generated by CodeScope / Ephemeral.ai*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codescope-${result.repo_name.replace('/', '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto px-6 animate-fade-in" style={{ paddingTop: '48px', paddingBottom: '80px' }}>
      {/* Header */}
      <div className="flex items-start justify-between mb-10">
        <div>
          <div className="flex items-baseline gap-3 mb-2">
            <h2
              className="font-semibold"
              style={{ fontSize: '24px', color: '#e4e4e7', letterSpacing: '-0.02em' }}
            >
              Report
            </h2>
            <span className="font-mono" style={{ fontSize: '16px', color: '#14b8a6' }}>
              {result.repo_name}
            </span>
          </div>
          <div className="flex items-center gap-3 text-xs font-mono" style={{ color: '#71717a' }}>
            <span>branch: {result.branch}</span>
            <span style={{ color: '#1e1e2e' }}>|</span>
            <span>{result.language}</span>
            <span style={{ color: '#1e1e2e' }}>|</span>
            <span>{formatDuration(result.duration_seconds)}</span>
            <span style={{ color: '#1e1e2e' }}>|</span>
            <span style={{ color: '#22c55e' }}>${result.cost_usd.toFixed(3)}</span>
          </div>
        </div>
        <button
          onClick={onNewAudit}
          className="text-sm font-mono transition-colors"
          style={{
            color: '#71717a',
            padding: '6px 16px',
            border: '1px solid #1e1e2e',
            borderRadius: '8px',
            background: 'transparent',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = '#52525b';
            e.currentTarget.style.color = '#e4e4e7';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#1e1e2e';
            e.currentTarget.style.color = '#71717a';
          }}
        >
          New Audit
        </button>
      </div>

      {/* Risk Score */}
      <div
        className="mb-8"
        style={{
          border: '1px solid #1e1e2e',
          borderRadius: '12px',
          background: '#12121a',
          padding: '28px',
        }}
      >
        <div
          className="font-semibold uppercase tracking-wider mb-5"
          style={{ fontSize: '11px', color: '#71717a', letterSpacing: '0.08em' }}
        >
          Risk Score
        </div>
        <RiskScore score={result.risk_score} />
      </div>

      {/* Severity Counts */}
      <div className="flex flex-wrap gap-3 mb-8">
        {SEVERITY_ORDER.map((sev) => (
          <button
            key={sev}
            onClick={() => setActiveSeverity(activeSeverity === sev ? null : sev)}
            className="transition-opacity"
            style={{
              opacity: activeSeverity && activeSeverity !== sev ? 0.4 : 1,
            }}
          >
            <SeverityCount severity={sev} count={severityCounts[sev]} />
          </button>
        ))}
      </div>

      {/* AI Summary */}
      <div
        className="mb-8"
        style={{
          border: '1px solid #1e1e2e',
          borderRadius: '12px',
          background: '#12121a',
          padding: '24px',
        }}
      >
        <div
          className="font-semibold uppercase tracking-wider mb-3"
          style={{ fontSize: '11px', color: '#14b8a6', letterSpacing: '0.08em' }}
        >
          AI Analysis Summary
        </div>
        <p style={{ fontSize: '14px', color: '#71717a', lineHeight: 1.7 }}>{result.summary}</p>
      </div>

      {/* Category Filters + Total Count */}
      <div className="flex flex-wrap items-center gap-2 mb-5">
        <button
          onClick={() => setActiveCategory(null)}
          className="font-mono transition-colors"
          style={{
            padding: '4px 10px',
            fontSize: '12px',
            borderRadius: '6px',
            border: `1px solid ${activeCategory === null ? 'rgba(20, 184, 166, 0.3)' : '#1e1e2e'}`,
            background: activeCategory === null ? 'rgba(20, 184, 166, 0.08)' : '#12121a',
            color: activeCategory === null ? '#14b8a6' : '#71717a',
          }}
        >
          All ({result.findings.length})
        </button>
        {categories.map((cat) => {
          const count = result.findings.filter((f) => f.category === cat).length;
          return (
            <button
              key={cat}
              onClick={() => setActiveCategory(activeCategory === cat ? null : cat)}
              className="font-mono transition-colors"
              style={{
                padding: '4px 10px',
                fontSize: '12px',
                borderRadius: '6px',
                border: `1px solid ${activeCategory === cat ? 'rgba(20, 184, 166, 0.3)' : '#1e1e2e'}`,
                background: activeCategory === cat ? 'rgba(20, 184, 166, 0.08)' : '#12121a',
                color: activeCategory === cat ? '#14b8a6' : '#71717a',
              }}
            >
              {cat} ({count})
            </button>
          );
        })}
        <span
          className="font-mono ml-auto"
          style={{ fontSize: '12px', color: '#52525b' }}
        >
          Total: {filteredFindings.length} finding{filteredFindings.length !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Findings */}
      <div className="space-y-3 mb-10">
        {filteredFindings.map((finding) => (
          <FindingCard key={finding.id} finding={finding} auditTaskId={result.task_id} repoUrl={result.repo_url} />
        ))}
        {filteredFindings.length === 0 && (
          <div className="text-center font-mono" style={{ padding: '32px 0', fontSize: '14px', color: '#52525b' }}>
            No findings match the selected filters.
          </div>
        )}
      </div>

      {/* Scan Layers Summary */}
      <div
        className="mb-10 overflow-hidden"
        style={{
          border: '1px solid #1e1e2e',
          borderRadius: '12px',
          background: '#12121a',
        }}
      >
        <div style={{ padding: '12px 16px', borderBottom: '1px solid #1e1e2e' }}>
          <span
            className="font-semibold uppercase tracking-wider"
            style={{ fontSize: '11px', color: '#71717a', letterSpacing: '0.08em' }}
          >
            Scan Layers
          </span>
        </div>
        {result.layers.map((layer, idx) => (
          <div
            key={layer.id}
            className="flex items-center gap-3 text-sm"
            style={{
              padding: '10px 16px',
              borderBottom: idx < result.layers.length - 1 ? '1px solid #1e1e2e' : 'none',
            }}
          >
            <span
              className="inline-block rounded-full"
              style={{ width: '6px', height: '6px', background: '#22c55e' }}
            />
            <span className="font-mono" style={{ width: '16px', fontSize: '12px', color: '#52525b' }}>{layer.id}</span>
            <span className="flex-1" style={{ fontSize: '14px', color: '#e4e4e7' }}>{layer.name}</span>
            <span className="font-mono" style={{ fontSize: '12px', color: '#71717a' }}>
              {layer.findings} findings
            </span>
            <span className="font-mono" style={{ width: '48px', textAlign: 'right', fontSize: '12px', color: '#52525b' }}>
              {layer.duration?.toFixed(1)}s
            </span>
          </div>
        ))}
      </div>

      {/* Download Actions */}
      <div className="flex flex-wrap gap-3">
        <button
          onClick={downloadMarkdown}
          className="flex items-center gap-2 font-mono transition-colors"
          style={{
            padding: '10px 20px',
            fontSize: '13px',
            color: '#e4e4e7',
            background: '#12121a',
            border: '1px solid #14b8a6',
            borderRadius: '8px',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = 'rgba(20, 184, 166, 0.08)';
            e.currentTarget.style.borderColor = '#14b8a6';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#12121a';
            e.currentTarget.style.borderColor = '#14b8a6';
          }}
        >
          <DownloadIcon />
          Download Report
        </button>
        <button
          onClick={downloadJSON}
          className="flex items-center gap-2 font-mono transition-colors"
          style={{
            padding: '10px 20px',
            fontSize: '13px',
            color: '#71717a',
            background: '#12121a',
            border: '1px solid #1e1e2e',
            borderRadius: '8px',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = '#52525b';
            e.currentTarget.style.color = '#e4e4e7';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#1e1e2e';
            e.currentTarget.style.color = '#71717a';
          }}
        >
          <DownloadIcon />
          Download JSON
        </button>
      </div>
    </div>
  );
}
